DATASET:
  NAME: "mscoco_bbox"
  ROOT_TRAIN: "demo_images"
  ROOT_EVAL: "demo_images"
  ROOT_TEST: "demo_images"
  JSON_TRAIN: "demo_images/instances_demo.json"
  JSON_EVAL: "demo_images/instances_demo.json"
  JSON_TEST: "demo_images/instances_demo.json"

DETECTOR:
  NAME: "cocobox_r50_bfpn4"
  ROOT_WEIGHT: "weights"
  DEPTH: 50
  NUM_CLASS: 80
  WIN_MINMAX: [[2, 128], [128, 256], [256, 512], [512, 9999]]
  NUMDETS: 100

EVAL:
  NMS_TOPK_P: 1000
  NMS_TH: 0.05
  NMS_IOU: 0.6
  MIN_SIZE: 513
  MAX_SIZE: 1025
  PAD_N: 128
  DEVICE: 0

TEST:
  NMS_TOPK_P: 1000
  NMS_TH: 0.5
  NMS_IOU: 0.6
  MIN_SIZE: 513
  MAX_SIZE: 1025
  PAD_N: 128
  DEVICE: 0

TRAIN:
  LOAD: False
  LOAD_TRAINED_LOG: True
  SAVE: False
  BACKBONE_PRETRAINED: True
  FREEZE_BN: True
  FREEZE_STAGES: 1
  MIN_SIZES: [513]
  MAX_SIZE: 1025
  PAD_N: 128
  NUM_EPOCH: 300
  DEVICES: [0]
  BATCH_SIZE: 1
  NUM_WORKERS: 0
  LR_BASE: 0.01
  LR_GAMMA: 0.1
  LR_SCHEDULE: [60000, 80000]
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  GRAD_CLIP: 10
  WARMUP_ITER: 50
  SEED: 0
