DATASET:
  NAME: "helmet_bbox"
  ROOT_TRAIN: "/home1/xyt/dataset/helmet/images"
  ROOT_EVAL: "/home1/xyt/dataset/helmet/images"
  ROOT_TEST: "demo_images"
  JSON_TRAIN: "/home1/xyt/dataset/helmet/annotations/helmet_train.json"
  JSON_EVAL: "/home1/xyt/dataset/helmet/annotations/helmet_val.json"
  JSON_TEST: "demo_images/instances_demo.json"

DETECTOR:
  NAME: "helmet_r50_bfpn4"
  ROOT_WEIGHT: "weights"
  DEPTH: 50
  NUM_CLASS: 5
  WIN_MINMAX: [[2, 128], [128, 256], [256, 512], [512, 9999]]
  NUMDETS: 100

EVAL:
  NMS_TOPK_P: 1000
  NMS_TH: 0.05
  NMS_IOU: 0.6
  MIN_SIZE: 513
  MAX_SIZE: 1025
  PAD_N: 128
  DEVICE: 0

TEST:
  NMS_TOPK_P: 1000
  NMS_TH: 0.5
  NMS_IOU: 0.6
  MIN_SIZE: 513
  MAX_SIZE: 1025
  PAD_N: 128
  DEVICE: 0

TRAIN:
  LOAD: False
  LOAD_TRAINED_LOG: True
  SAVE: True
  BACKBONE_PRETRAINED: True
  FREEZE_BN: True
  FREEZE_STAGES: 1
  MIN_SIZES: [513, 513, 641]
  MAX_SIZE: 1025
  PAD_N: 128
  NUM_EPOCH: 12
  DEVICES: [0,1,2,3]
  BATCH_SIZE: 16
  NUM_WORKERS: 16
  LR_BASE: 0.01
  LR_GAMMA: 0.1
  LR_SCHEDULE: [2400, 2800]
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  GRAD_CLIP: 10
  WARMUP_ITER: 50
  SEED: 0
